#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;

use Benchmark::Command;

Benchmark::Command::run(0, {
    'perl'           => [$^X, "-e1"],
    'load_periswrap' => [$^X, "-MPerinci::Sub::Wrapper", "-e", 1],
    'wrap_minimal'   => [$^X, "-MPerinci::Sub::Wrapper=wrap_sub", "-e", q!wrap_sub(sub=>sub{}, meta=>{v=>1.1})!],
    'wrap_typical'   => [$^X, "-MPerinci::Sub::Wrapper=wrap_sub", "-e", q!wrap_sub(sub=>sub{}, meta=>{v=>1.1, summary=>"Some summary", args=>{a1=>{schema=>"int*", req=>1, pos=>0}, a2=>{schema=>"str"}, a3=>{schema=>"str*",}, a4=>{schema=>"str"}, a5=>{schema=>"str*"}}})!],
});
